ALTER TABLE "RSVP" ADD COLUMN "checkedIn" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "RSVP" ADD COLUMN "checkedInAt" TIMESTAMP(3);
ALTER TABLE "GuestRSVP" ADD COLUMN "checkedIn" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "GuestRSVP" ADD COLUMN "checkedInAt" TIMESTAMP(3);
