-- Add muteInAppNotifications to User
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "muteInAppNotifications" BOOLEAN NOT NULL DEFAULT false;

-- Add new NotificationType enum values
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEMBER_ADDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEMBER_REMOVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ROLE_CHANGED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EVENT_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EVENT_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'COMMENT_ON_EVENT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INVITE_ACCEPTED';
