ALTER TABLE "RSVPPlusOne" ADD COLUMN "status" "RSVPStatus";
ALTER TABLE "RSVPPlusOne" ADD COLUMN "checkedIn" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "RSVPPlusOne" ADD COLUMN "checkedInAt" TIMESTAMP(3);
